### ISSUE TITLE
Infinite import loop with 2021.2.9

### ISSUE THREAD

**Issue by ZackOfAllTrades** [atteneder/glTFastDemo#5]
Assets/StreamingAssets/glTF-Sample-Models/2.0 is a symbolic link. Using symlinks in Unity projects may cause your project to become corrupted if you create multiple references to the same asset, use recursive symlinks or use symlinks to share assets between projects used with different versions of Unity. Make sure you know what you are doing.

An infinite import loop has been detected. The following Assets were imported multiple times, but no changes to them have been detected. Please check if any custom code is trying to import them:
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/d_Duplicate@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/ShaderLibrary/API/Metal.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.atteneder.gltfast/Runtime/Shader/Legacy/glTF-pbrMetallicRoughness-Opaque.shadergraph(modified date 2022-02-01T18:55:20.1899571Z)
Assets/link.xml(modified date 2022-02-01T18:31:46.4809919Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/d_LeftArrow@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/ShaderLibrary/API/Validate.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.shadergraph/Editor/Resources/GraphView/Nodes/PreviewCollapse@2x.png(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.shadergraph/Editor/Generation/Targets/BuiltIn/ShaderLibrary/BuiltInDOTSInstancing.hlsl(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.shadergraph/Editor/Resources/Styles/Controls/TextControlView.uss(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.shadergraph/Editor/Generation/Targets/BuiltIn/ShaderLibrary/DeclareDepthTexture.hlsl(modified date 2022-01-17T05:43:16Z)
Assets/Resources/readme.txt(modified date 2022-02-01T18:31:46.46299Z)
Packages/com.unity.burst/CHANGELOG.md(modified date 2021-11-24T17:03:20Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/d_Shade.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/LayoutCustom@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/Fluorescent@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.atteneder.gltfast/Runtime/Shader/Built-In/glTFIncludes/glTFUnityStandardMeta.cginc(modified date 2022-02-01T18:55:20.1699567Z)
Packages/com.unity.render-pipelines.core/ShaderLibrary/API/GLES3.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.shadergraph/Editor/Generation/Targets/BuiltIn/Editor/ShaderGraph/Includes/SpriteNormalPass.hlsl(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.render-pipelines.core/package.json(modified date 2022-01-17T05:43:08Z)
Packages/com.unity.burst/Unity.Burst.Unsafe.xml(modified date 2021-11-24T17:03:20Z)
Packages/com.unity.shadergraph/Editor/Resources/Styles/InspectorView.uss(modified date 2022-01-17T05:43:16Z)
Packages/com.atteneder.ktx/Runtime/Plugins/x86_64/ktx_unity.bundle/Contents/Info.plist(modified date 2021-11-23T14:27:28.2880002Z)
Packages/com.unity.render-pipelines.core/ShaderLibrary/MetaPass.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.shadergraph/ShaderGraphLibrary/Nature/SpeedTree8Billboard.shadersubgraph(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.settings-manager/Third Party Notices.md(modified date 2020-08-05T14:39:50Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/d_renderdoc.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.shadergraph/Editor/Resources/Icons/Settings_Flyout_9slice.png(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/BrightSky.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/d_MediumAreaLight.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/ShaderLibrary/SpaceFillingCurves.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.atteneder.gltfast/Runtime/Shader/Legacy/glTF-pbrMetallicRoughness-Blend-double.shadergraph(modified date 2022-02-01T18:55:20.1839585Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/Environment.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/d_Overcast@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/CloudySky@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.shadergraph/Editor/Generation/Targets/BuiltIn/ShaderLibrary/ShaderVariablesFunctions.deprecated.hlsl(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/d_Camera1@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.shadergraph/Editor/Resources/Styles/CustomSlotLabelField.uss(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.ugui/package.json(modified date 2022-01-17T05:43:00Z)
Packages/com.unity.render-pipelines.core/ShaderLibrary/PhysicalCamera.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/Layout2@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.mathematics/package.json(modified date 2021-11-08T17:27:47Z)
Packages/com.atteneder.gltf-demo/Runtime/Scenes/FastMassLoader.unity(modified date 2022-02-01T18:31:45.6006762Z)
Packages/com.unity.render-pipelines.core/Editor/PostProcessing/LensFlareResource/CircleFlareThumbnail.png(modified date 2022-01-17T05:43:12Z)
Packages/com.unity.shadergraph/Editor/Resources/UXML/GraphSubWindow.uxml(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.shadergraph/ShaderGraphLibrary/LODDitheringTransition.hlsl(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/ProbeVolume/ProbePlacement.cs.hlsl(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/MediumAreaLight@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/d_DecorativeLight@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.ide.rider/CHANGELOG.md(modified date 2022-01-13T19:19:47Z)
Packages/com.atteneder.gltfast/Runtime/Shader/Legacy/glTF-pbrSpecularGlossiness-Opaque-double.shadergraph(modified date 2022-02-01T18:55:20.1979578Z)
Packages/com.unity.render-pipelines.core/ShaderLibrary/BC6H.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/ProbeVolume/ProbeVolumeSubdivide.compute(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.shadergraph/Editor/Resources/Styles/Controls/PopupControlView.uss(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/d_IntenseAreaLight.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.shadergraph/Editor/Generation/Targets/BuiltIn/Editor/ShaderGraph/Templates/ShaderPass.template(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.searcher/Editor/Resources/FlatSkin/Font/Roboto-Regular.ttf(modified date 2021-10-07T18:43:08Z)
Packages/com.atteneder.gltf-test-framework/Runtime/Export/Models/QuadCube.fbx(modified date 2022-02-01T18:55:24.6585799Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/Layout1@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.atteneder.gltfast/ChangeLog.md(modified date 2022-02-01T18:55:19.4498016Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/Link@2x.png(modified date 2022-01-17T05:43:12Z)
Packages/com.unity.modules.physics/package.json(modified date 2022-01-17T05:42:58Z)
Packages/com.unity.shadergraph/Editor/Generation/Targets/BuiltIn/ShaderLibrary/UnityInput.hlsl(modified date 2022-01-17T05:43:16Z)
Packages/com.atteneder.gltfast/Runtime/Shader/Built-In/glTFIncludes/glTFUnityStandardCore.cginc(modified date 2022-02-01T18:55:20.1659566Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/CenterLight.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Textures/UIArrowDown.png(modified date 2022-01-17T05:43:12Z)
Packages/com.unity.shadergraph/ShaderGraphLibrary/ShaderVariablesFunctions.hlsl(modified date 2022-01-17T05:43:16Z)
Packages/com.atteneder.gltfast/Editor/Resources/Dependency.uxml(modified date 2022-02-01T18:55:19.9969517Z)
Packages/com.unity.modules.jsonserialize/package.json(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Runtime/Lighting/ProbeVolume/ProbeReferenceVolume.Debug.cs.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.atteneder.gltfast/Runtime/Shader/SubGraphs/Emission.shadersubgraph(modified date 2022-02-01T18:55:20.2079579Z)
Packages/com.atteneder.gltfast/Runtime/Shader/Legacy/glTF-pbrMetallicRoughness-Blend.shadergraph(modified date 2022-02-01T18:55:20.1859573Z)
Packages/com.unity.shadergraph/Editor/Generation/Templates/BuildSurfaceDescriptionInputs.template.hlsl(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.shadergraph/Editor/Resources/Styles/ReorderableSlotListView.uss(modified date 2022-01-17T05:43:16Z)
Packages/com.atteneder.gltfast/Runtime/Shader/Built-In/glTFIncludes/glTFUnityStandardCoreForward.cginc(modified date 2022-02-01T18:55:20.1669574Z)
Packages/com.atteneder.gltf-demo/Runtime/ShaderVariants/glTFBuiltIn.shadervariants(modified date 2022-02-01T18:31:45.6256776Z)
Packages/com.unity.settings-manager/CHANGELOG.md(modified date 2020-08-05T14:39:50Z)
Packages/com.unity.settings-manager/package.json(modified date 2020-08-05T14:39:50Z)
Packages/com.atteneder.gltfast/Editor/Resources/Dependency-style.uss(modified date 2022-02-01T18:55:19.9959518Z)
Packages/com.unity.shadergraph/Editor/Resources/Styles/HelpBoxRow.uss(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/d_CenterLight.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.shadergraph/Editor/Resources/Styles/PixelCacheProfiler.uss(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/d_Camera1.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.shadergraph/Editor/Resources/Styles/Controls/GradientSlotControlView.uss(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/Shade@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.shadergraph/Editor/Resources/Styles/ColorMode.uss(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/Shade.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/ShaderLibrary/API/Switch.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.searcher/LICENSE.md(modified date 2021-10-07T18:43:08Z)
Packages/com.atteneder.gltf-demo/Runtime/SampleSets/glTF-Sample-Models.asset(modified date 2022-02-01T18:31:45.595676Z)
Packages/com.unity.modules.unitywebrequesttexture/package.json(modified date 2022-01-17T05:43:06Z)
Packages/com.unity.render-pipelines.core/Runtime/Lighting/ProbeVolume/DecodeSH.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/CloudySky.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.shadergraph/Editor/Generation/Targets/BuiltIn/Editor/ShaderGraph/Includes/SpriteUnlitPass.hlsl(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/PresetKick_Left.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/d_BlueSky.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/UpSnatchFocused.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.shadergraph/Editor/Resources/UXML/Blackboard/SGBlackboardField.uxml(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.test-framework/CHANGELOG.md(modified date 2021-10-19T13:28:56Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/BlueSky.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/IntenseAreaLight.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/d_Fluorescent.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/CubeToLatlong.shader(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.shadergraph/Editor/Generation/Targets/BuiltIn/Editor/ShaderGraph/Includes/ShaderPass.hlsl(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/d_SunPosition@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/ShaderLibrary/ImageBasedLighting.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.ugui/CHANGELOG.md(modified date 2022-01-17T05:43:00Z)
Packages/com.unity.render-pipelines.core/Runtime/PostProcessing/Shaders/ffx/ffx_a.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.render-pipelines.core/ShaderLibrary/CommonShadow.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.shadergraph/Editor/Generation/Targets/BuiltIn/Editor/ShaderGraph/Includes/PBRForwardAddPass.hlsl(modified date 2022-01-17T05:43:16Z)
Assets/StreamingAssets/glTF-Sample-Models/2.0(modified date 2022-02-01T18:31:46.4709896Z)
Packages/com.unity.render-pipelines.core/ShaderLibrary/API/GLCore.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.shadergraph/Editor/Resources/Icons/sg_subgraph_icon.png(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Widgets/DebugUIVBox.prefab(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/SunPosition.png(modified date 2022-01-17T05:43:12Z)
Packages/com.unity.shadergraph/Editor/Generation/Targets/BuiltIn/ShaderLibrary/Shadows.hlsl(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.ext.nunit/CHANGELOG.md(modified date 2020-12-07T22:12:08Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/d_Link@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/Advanced_UnPressed_mini.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/d_ClearSky@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Compositor.shader(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.shadergraph/Editor/Resources/GraphView/Nodes/NodeChevronDown@2x.png(modified date 2022-01-17T05:43:16Z)
Packages/com.unity.render-pipelines.core/ShaderLibrary/Macros.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.shadergraph/package.json(modified date 2022-01-17T05:43:06Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/DecorativeLight.png(modified date 2022-01-17T05:43:10Z)
Packages/com.atteneder.gltfast/Runtime/Shader/SubGraphs/BaseColor.shadersubgraph(modified date 2022-02-01T18:55:20.2059585Z)
Packages/com.unity.render-pipelines.core/Editor/LookDev/Icons/d_RightArrow.png(modified date 2022-01-17T05:43:10Z)
Packages/com.atteneder.draco/THIRD PARTY NOTICES.md(modified date 2022-01-20T14:22:44.335Z)
Packages/com.atteneder.gltf-test-framework/Runtime/Export/Materials/BaseColorTextureFade.mat(modified date 2022-02-01T18:55:23.539104Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/Overcast@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/d_Fluorescent@2x.png(modified date 2022-01-17T05:43:10Z)
Packages/com.atteneder.gltfast/Runtime/Shader/SubGraphs/Unlit.shadersubgraph(modified date 2022-02-01T18:55:20.2209582Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/d_SunriseSunset.png(modified date 2022-01-17T05:43:10Z)
Packages/com.atteneder.gltf-test-framework/Runtime/Export/Materials/Metallic 5.mat(modified date 2022-02-01T18:55:23.5541075Z)
Packages/com.atteneder.gltfast/Runtime/Shader/glTF-unlit.shadergraph(modified date 2022-02-01T18:55:20.2259583Z)
Packages/com.unity.settings-manager/README.md(modified date 2020-08-05T14:39:50Z)
Packages/com.unity.render-pipelines.core/ShaderLibrary/Debug.hlsl(modified date 2022-01-17T05:43:14Z)
Packages/com.unity.shadergraph/CHANGELOG.md(modified date 2022-01-17T05:43:06Z)
Packages/com.unity.render-pipelines.core/Editor/Lighting/Icons/LightUnitIcons/InteriorLight@2x.png(modified date 2022-01-1<message truncated>

**Comment by atteneder** [comment]
fyi: I'm actively (mis-)using this repo for development and testing. It has become more than just a demo, which is not good. I intend to move tests and such to a dedicated repo again and simplify this one. Once that is done, I presume that errors like this one will be gone.

hth

**Comment by NickChalvatzakis** [comment]
@atteneder What Unity version are you using for your tests? Because for my project i've alsso been using 2021(.3.30f1) and i have similar problems with OP

**Comment by atteneder** [comment]
I'm currently on [Unity 6 Preview (6000.0.0b12)](https://github.com/atteneder/glTFastDemo/blob/main/projects/glTF-demo-minsize/ProjectSettings/ProjectVersion.txt).

Most of the tests reside in the [package source](https://github.com/Unity-Technologies/com.unity.cloud.gltfast/tree/main/Tests) nowadays. More to come.

I advice you to not use this repository for now until a better test setup arrives.
